/**/usrp_driver_node:
  ros__parameters:
    device_args: "type=b200"
    freq_hz: 2.398e9
    rate_hz: 5e6
    gain_db: 10.0
    channel: 0

/**/rf_detector_node:
  ros__parameters:
    nfft:        2048
    win_size:    2048
    hop:         512
    buffer_size: 500000
    conf_thresh: 0.2

/**/scoreboard_node:
  ros__parameters:
    aggregation: "max"
