#!/usr/bin/env python3
from rf_pipeline.rf_detector import RfDetectorNode
import rclpy
import sys

if __name__ == "__main__":
    rclpy.init(args=sys.argv)
    node = RfDetectorNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
