#!/usr/bin/env python3
import rclpy
from rf_pipeline.yolo_detector import YoloDetectorNode
import sys

if __name__ == "__main__":
    rclpy.init(args=sys.argv[1:])
    node = YoloDetectorNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()

